apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: initial-default-resources
  namespace: tap-namespace-provisioning
  annotations:
    kapp.k14s.io/create-strategy: fallback-on-update
    kapp.k14s.io/change-rule.0: delete before deleting serviceaccount/provisioner
    kapp.k14s.io/change-rule.1: delete before deleting serviceaccounts
spec:
  serviceAccountName: provisioner

  syncPeriod: 10m0s
  fetch:
  - git:
      ref: origin/main
      subPath: default-resources/git-custom/defalut-reousrces/resources
      url: https://github.com/odinnordico/namespace-provisioner-resources.git
    path: initial-resources
  template:
    - ytt:
        paths:
        - initial-resources
  deploy:
    - kapp:
        rawOptions: ["--dangerous-allow-empty-list-of-resources=true", "--dangerous-override-ownership-of-existing-resources=true"]
